package com.risquanter.register.http.controllers

import zio.*
import sttp.tapir.server.ServerEndpoint
import com.risquanter.register.http.endpoints.SimulationEndpoints
import com.risquanter.register.services.SimulationService
import com.risquanter.register.http.responses.SimulationResponse
import com.risquanter.register.domain.data.iron.ValidationUtil
import com.risquanter.register.domain.errors.ValidationFailed
import com.risquanter.register.domain.data.Simulation
import io.github.iltotore.iron.autoRefine

/** Controller for Simulation HTTP endpoints
  * Handles request validation and delegates to service layer
  */
class SimulationController private (simService: SimulationService)
    extends BaseController
    with SimulationEndpoints {

  val create: ServerEndpoint[Any, Task] = createEndpoint.serverLogic { req =>
    val validation = for {
      name <- ValidationUtil.refineName(req.name)
      minLoss <- ValidationUtil.refineNonNegativeLong(req.minLoss, "minLoss")
      maxLoss <- ValidationUtil.refineNonNegativeLong(req.maxLoss, "maxLoss")
      likelihoodId <- ValidationUtil.refineNonNegativeLong(req.likelihoodId, "likelihoodId")
      probability <- ValidationUtil.refineProbability(req.probability)
    } yield Simulation(
      id = 0L, // ID will be generated by repository
      name = name,
      minLoss = minLoss,
      maxLoss = maxLoss,
      likelihoodId = likelihoodId,
      probability = probability
    )

    val program = validation match {
      case Left(errors) => ZIO.fail(ValidationFailed(errors))
      case Right(sim) =>
        simService.create(req).map(SimulationResponse.fromSimulation)
    }

    program.either
  }

  val getAll: ServerEndpoint[Any, Task] = getAllEndpoint.serverLogicSuccess { _ =>
    simService.getAll.map(_.map(SimulationResponse.fromSimulation))
  }

  val getById: ServerEndpoint[Any, Task] = getByIdEndpoint.serverLogicSuccess { idStr =>
    ZIO
      .attempt(idStr.toLong)
      .flatMap(simService.getById)
      .map(_.map(SimulationResponse.fromSimulation))
  }

  override val routes: List[ServerEndpoint[Any, Task]] =
    List(create, getAll, getById)
}

object SimulationController {
  val makeZIO: ZIO[SimulationService, Nothing, SimulationController] = for {
    simService <- ZIO.service[SimulationService]
  } yield new SimulationController(simService)
}
